version: '2'
services:
  web:
    restart: always
    build: .
    expose:
      - "9095"
  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
